### ISSUE TITLE
Angular ts files.

### ISSUE THREAD

**Issue by potgieterdl** [hawtio/hawtio-core-dts#1]
Hi,

The angular files dont support generics, so cant extend $resource for instance. Can these be updated or removed and rather depend on http://definitelytyped.org/tsd/?

**Comment by gashcrumb** [comment]
Updated here -> https://github.com/hawtio/hawtio-core-dts/commit/37ea450615cb3bf56f23b26f47372ca62e1472af

Better late than never, right?
